---

galaxy_info:
  role_name: keepalived
  description: Install keepalived
  author: sparknsh
  company: Rebel Media, Inc.
  license: MIT
  min_ansible_version: 2.5
  github_branch: master
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - system
    - development
    - cloud
    - keepalive
    - keepalived
    - networking

dependencies: []
