---
- name: Hard set the hostname
  hostname: name={{ fqdn_host }}

- name: Add host entry
  lineinfile:
    dest=/etc/hosts
    regexp=" {{ fqdn_host }} ?"
    line="{{ ipv4 }} {{ fqdn_host }}"
    owner=root
    group=root
    mode=0644

- name: Install FreeIPA Client
  action: apt pkg={{ item }} state=present
  with_items:
    - freeipa-client

- name: Run ipa-client-install
  become: true
  command: /usr/sbin/ipa-client-install --mkhomedir --unattended --no-ntp --principal={{ admin_user }} --password={{ admin_password }}


