Vagrant.configure("2") do |config|
  config.vm.box = "senglin/win-10-enterprise-vs2015community"
  config.vm.box_version = "1.0.0"
  config.vm.hostname = "windows"
  config.vm.network :private_network, ip: "10.0.1.20",
    virtualbox__intnet: "intnet"
end
