Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end
  config.vm.define "centos"
  config.vm.box = "centos/7"
  config.vm.hostname = "centos"
  #config.vm.network :private_network, ip: "10.0.1.10",
  #  virtualbox__intnet: "intnet"
  #config.ssh.insert_key = false
  #config.vm.provision "ansible" do |ansible|
  #  ansible.verbose = "v"
  #  ansible.playbook = "provisioning/playbook.yml"
  #  ansible.groups = {
  #    "ipaclient" => ["ipaclient"],
  #  }
  #  ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
  config.vm.provision "shell", inline: <<-SHELL
	  mkdir -p ~root/.ssh
    cp ~vagrant/.ssh/auth* ~root/.ssh
    sudo yum install wget -y
    sudo mkdir -p /usr/lib/dracut/modules.d/01test
    sudo wget https://gist.githubusercontent.com/lalbrekht/e51b2580b47bb5a150bd1a002f16ae85/raw/80060b7b300e193c187bbcda4d8fdf0e1c066af9/gistfile1.txt -O /usr/lib/dracut/modules.d/01test/module-setup.sh
    sudo chmod +x /usr/lib/dracut/modules.d/01test/module-setup.sh
    sudo wget https://gist.githubusercontent.com/lalbrekht/ac45d7a6c6856baea348e64fac43faf0/raw/69598efd5c603df310097b52019dc979e2cb342d/gistfile1.txt -O /usr/lib/dracut/modules.d/01test/test.sh
    sudo chmod +x /usr/lib/dracut/modules.d/01test/test.sh
    sudo dracut -f -v
    sudo grub2-mkconfig -o /boot/grub2/grub.cfg
    sudo reboot
  SHELL
end
