Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end
  config.vm.define "server"
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "server"
  config.vm.network :private_network, ip: "10.0.1.1",
    virtualbox__intnet: "intnet"
  config.ssh.insert_key = false
  #config.vm.provision "ansible" do |ansible|
  #  ansible.verbose = "v"
  #  ansible.playbook = "provisioning/playbook.yml"
  #  ansible.groups = {
  #    "ipaclient" => ["ipaclient"],
  #  }
  #  ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
  #end
end
