# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 1
  end

  # Define two VMs with static private IP addresses.
  boxes = [
    { :name => "node0", :ip => "192.168.7.150" },
    { :name => "node1", :ip => "192.168.7.151" },
    { :name => "node2", :ip => "192.168.7.152" },
    { :name => "node3", :ip => "192.168.7.153" },
    { :name => "node4", :ip => "192.168.7.154" },
    { :name => "node5", :ip => "192.168.7.155" }
  ]

  # Provision each of the VMs.
  boxes.each do |opts|
    
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
      
      if opts[:name] == "node5"
        config.vm.provision "ansible" do |ansible|
          ansible.playbook = "playbooks/provision.yml"
          ansible.inventory_path = "inventory"
          ansible.limit = "all"
          ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
        end
      end
    end
  end

end
