---
# defaults file for ansible-etcd

# List of this member's client URLs to advertise to the rest of the cluster
etcd_advertise_client_urls:
  - "{{ etcd_url_scheme }}://{{ etcd_cluster_ip }}:{{ etcd_client_port }}"

etcd_client_legacy_port: 4001

etcd_client_port: 2379

# Defines Ansible group for cluster hosts
etcd_cluster_group: etcd_cluster

etcd_cluster_interface: enp0s8

# Define master cluster node (Important during bootstrapping cluster)
etcd_cluster_master: "{{ groups[etcd_cluster_group][0] }}"

# Defines whether or not etcd is configured
etcd_config: true

# Defines the directory to store cluster data
etcd_data_dir: /var/lib/etcd

# List of this member's peer URLs to advertise to the rest of the cluster
etcd_initial_advertise_peer_urls:
  - "{{ etcd_peer_url_scheme }}://{{ etcd_cluster_ip }}:{{ etcd_peer_port }}"

# Initial cluster state ("new" or "existing")
etcd_initial_cluster_state: new

etcd_initial_cluster_token: vagrant-etcd-cluster

etcd_listen_client_urls:
  - "{{ etcd_url_scheme }}://{{ etcd_cluster_ip }}:{{ etcd_client_port }}"
  - "{{ etcd_url_scheme }}://127.0.0.1:{{ etcd_client_port }}"

# List of URLs to listen on for peer traffic
etcd_listen_peer_urls:
  - "{{ etcd_peer_url_scheme }}://{{ etcd_cluster_ip }}:{{ etcd_peer_port }}"

etcd_peer_legacy_port: 7001
etcd_peer_port: 2380
etcd_peer_url_scheme: http

# Define if you would like to reset the cluster
etcd_reset_cluster: false

etcd_url_scheme: http
