---
- name: redhat | Installing etcd
  yum:
    name: etcd
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != 'Fedora'

- name: redhat | Installing etcd
  dnf:
    name: etcd
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == 'Fedora'
