---
- hosts: nodes
  sudo: yes

  vars_files:
    - vars.yml

  roles:
    - glusterfs
    - nginx
    - haproxy
    - keepalived
    - etcd


  pre_tasks:
    - name: Install python
      raw: sudo apt-get -y install python-simplejson

    - name: Sysctrl sets
      sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: 1
        state: present

  tasks:
    - name: Ensure Gluster brick and mount directories exist.
      file: "path={{ item }} state=directory mode=0775"
      with_items:
        - "{{ gluster_brick_dir }}"
        - "{{ gluster_mount_dir }}"

    - name: Configure Gluster volume.
      gluster_volume:
        state: present
        name: "{{ gluster_brick_name }}"
        brick: "{{ gluster_brick_dir }}"
        replicas: 6
        cluster: "{{ groups.nodes | join(',') }}"
        host: "{{ inventory_hostname }}"
        force: yes
      run_once: true

    - name: Ensure Gluster volume is mounted.
      mount:
        name: "{{ gluster_mount_dir }}"
        src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted

    - name: Update apt
      apt: update_cache=yes

    - name: Install latest mc
      apt: name=mc state=latest

    - name: Generate /etc/hosts file
      template:
        src={{ playbook_dir }}/templates/etc/hosts.j2
        dest=/etc/hosts

    - name: Generate HTML file
      template:
        src={{ playbook_dir }}/templates/www/index.html.j2
        dest=/mnt/nodes/www/index.html