---
#NTP
ntp_enabled: true
ntp_timezone: Europe/Moscow
ntp_manage_config: true
ntp_area: 'Europe'
ntp_restrict:
  - "127.0.0.1"
  - "::1"

# Gluster configuration.
gluster_mount_dir: /mnt/nodes/www
gluster_brick_dir: /srv/nodes/www
gluster_brick_name: www

# Nginx configuration.
nginx_package_name: "nginx"
nginx_service_state: started
nginx_service_enabled: true
nginx_remove_default_vhost: true
nginx_vhosts:
  - listen: "8080"
    server_name: "project.local"
    root: "/mnt/nodes/www"
    index: "index.php index.html index.htm"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "project.local.conf"

# HAProxy configuration.
haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /var/lib/haproxy
haproxy_user: haproxy
haproxy_group: haproxy

haproxy_frontend_name: 'hafrontend'
haproxy_frontend_bind_address: '192.168.7.160'
haproxy_frontend_port: 80
haproxy_frontend_mode: 'http'

haproxy_backend_name: 'habackend'
haproxy_backend_mode: 'http'
haproxy_backend_balance_method: 'roundrobin'
haproxy_backend_httpchk: 'HEAD / HTTP/1.1\r\nHost:localhost'

haproxy_backend_servers:
  - name: app0
    address: 192.168.7.150:8080
  - name: app1
    address: 192.168.7.151:8080
  - name: app2
    address: 192.168.7.152:8080
  - name: app3
    address: 192.168.7.153:8080
  - name: app4
    address: 192.168.7.154:8080
  - name: app5
    address: 192.168.7.155:8080

# Keepalived

keepalived__nonlocal_bind: true
keepalived__conf_tpl: "{{ playbook_dir }}/templates/keepalived.conf.j2"
 
# ETCD
# List of this member's client URLs to advertise to the rest of the cluster
etcd_advertise_client_urls:
  - "{{ etcd_url_scheme }}://{{ etcd_cluster_ip }}:{{ etcd_client_port }}"

etcd_client_legacy_port: 4001

etcd_client_port: 2379

# Defines Ansible group for cluster hosts
etcd_cluster_group: etcd_cluster

etcd_cluster_interface: enp0s8

# Define master cluster node (Important during bootstrapping cluster)
etcd_cluster_master: "{{ groups[etcd_cluster_group][0] }}"

# Defines whether or not etcd is configured
etcd_config: true

# Defines the directory to store cluster data
etcd_data_dir: /var/lib/etcd

# List of this member's peer URLs to advertise to the rest of the cluster
etcd_initial_advertise_peer_urls:
  - "{{ etcd_peer_url_scheme }}://{{ etcd_cluster_ip }}:{{ etcd_peer_port }}"

# Initial cluster state ("new" or "existing")
etcd_initial_cluster_state: new

etcd_initial_cluster_token: etcd-cluster

etcd_listen_client_urls:
  - "{{ etcd_url_scheme }}://{{ etcd_cluster_ip }}:{{ etcd_client_port }}"
  - "{{ etcd_url_scheme }}://127.0.0.1:{{ etcd_client_port }}"

# List of URLs to listen on for peer traffic
etcd_listen_peer_urls:
  - "{{ etcd_peer_url_scheme }}://{{ etcd_cluster_ip }}:{{ etcd_peer_port }}"

etcd_peer_legacy_port: 7001
etcd_peer_port: 2380
etcd_peer_url_scheme: http

# Define if you would like to reset the cluster
etcd_reset_cluster: false

etcd_url_scheme: http

#Patroni
patroni_dcs: etcd
patroni_dcs_exists: true


