---

- name: Converge
  hosts: all
  become: true
  gather_timeout: 300

  vars_files:
    - vars.yml

  pre_tasks:

    - name: APT Cache
      apt:
        update_cache: true
      when: ansible_pkg_mgr == 'apt'
      changed_when: false

    - name: YUM Cache
      yum:
        update_cache: true
      when: ansible_pkg_mgr == 'yum'
      changed_when: false

    - name: DNF Cache
      dnf:
        update_cache: true
      when: ansible_pkg_mgr == 'dnf'
      changed_when: false

    - name: Ensure that the procps package is installed
      package:
        name: procps
        state: present
      when: ansible_os_family == 'Debian'

    - name: Ensure that the procps package is installed
      package:
        name: procps
        state: present
      when:
        - ansible_distribution_major_version <= '6'
        - ansible_os_family == 'RedHat'

    - name: Ensure that the procps-ng package is installed
      package:
        name: procps-ng
        state: present
      when:
        - ansible_distribution_major_version >= '7'
        - ansible_os_family == 'RedHat'

  roles:
    - role: sparknsh.%ANSIBLE_GALAXY%
